apiVersion: apps/v1
kind: Deployment
metadata:              
  name: compras
spec:                 
  selector:                 
    matchLabels:             
      app: compras     
  replicas: 2              
  template:     
    metadata:                      
      labels:               
        app: compras             
    spec:                       
      containers:              
        - name: compras                      
          image: docker.io/ren776/compras:1.5
          ports:                 
            - containerPort: 9000
