apiVersion: apps/v1
kind: Deployment
metadata:              
  name: frontend
spec:                 
  selector:                 
    matchLabels:             
      app: frontend     
  replicas: 2              
  template:     
    metadata:                      
      labels:               
        app: frontend             
    spec:                       
      containers:              
        - name: frontend                      
          image: docker.io/ren776/frontend:1.0
          ports:                 
            - containerPort: 8080
