apiVersion: apps/v1
kind: Deployment
metadata:              
  name: solicitud
spec:                 
  selector:                 
    matchLabels:             
      app: solicitud     
  replicas: 2              
  template:     
    metadata:                      
      labels:               
        app: solicitud             
    spec:                       
      containers:              
        - name: solicitud                      
          image: docker.io/ren776/solicitud:1.5
          ports:                 
            - containerPort: 4080
